# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(default=b'', max_length=100, verbose_name=b'\xe7\x9c\x81\xe4\xbb\xbd')),
                ('city', models.CharField(default=b'', max_length=100, verbose_name=b'\xe5\x9f\x8e\xe5\xb8\x82')),
                ('district', models.CharField(default=b'', max_length=100, verbose_name=b'\xe5\x8c\xba\xe5\x9f\x9f')),
                ('address', models.CharField(default=b'', max_length=100, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86\xe5\x9c\xb0\xe5\x9d\x80')),
                ('signer_name', models.CharField(default=b'', max_length=30, verbose_name=b'\xe7\xad\xbe\xe6\x94\xb6\xe4\xba\xba')),
                ('signer_mobile', models.CharField(default=b'', max_length=11, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba\xe7\x94\xb5\xe8\xaf\x9d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u6536\u8d27\u5730\u5740',
                'verbose_name_plural': '\u6536\u8d27\u5730\u5740',
            },
        ),
        migrations.CreateModel(
            name='UserFav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u6536\u85cf',
                'verbose_name_plural': '\u7528\u6237\u6536\u85cf',
            },
        ),
        migrations.CreateModel(
            name='UserLeavingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.IntegerField(choices=[(1, b'\xe7\x95\x99\xe8\xa8\x80'), (2, b'\xe6\x8a\x95\xe8\xaf\x89'), (3, b'\xe8\xaf\xa2\xe9\x97\xae'), (4, b'\xe5\x94\xae\xe5\x90\x8e'), (5, b'\xe6\xb1\x82\xe8\xb4\xad')], default=1, help_text=b'\xe7\x95\x99\xe8\xa8\x80\xe7\xb1\xbb\xe5\x9e\x8b\xef\xbc\x9a1(\xe7\x95\x99\xe8\xa8\x80)\xef\xbc\x8c2(\xe6\x8a\x95\xe8\xaf\x89)\xef\xbc\x8c3(\xe8\xaf\xa2\xe9\x97\xae)\xef\xbc\x8c4(\xe5\x94\xae\xe5\x90\x8e)\xef\xbc\x8c5(\xe6\xb1\x82\xe8\xb4\xad)', verbose_name=b'\xe7\x95\x99\xe8\xa8\x80\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('subject', models.CharField(default=b'', max_length=200, verbose_name=b'\xe4\xb8\xbb\xe9\xa2\x98')),
                ('message', models.TextField(default=b'', help_text=b'\xe5\x86\x85\xe5\xae\xb9', verbose_name=b'\xe5\x86\x85\xe5\xae\xb9')),
                ('file', models.FileField(help_text=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe7\x9a\x84\xe6\x96\x87\xe4\xbb\xb6', upload_to=b'message/images/', verbose_name=b'\xe4\xb8\x8a\xe4\xbc\xa0\xe7\x9a\x84\xe6\x96\x87\xe4\xbb\xb6')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u7528\u6237\u7559\u8a00',
                'verbose_name_plural': '\u7528\u6237\u7559\u8a00',
            },
        ),
    ]
