# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-07 13:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.IntegerField(default=0, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe6\x95\xb0\xe9\x87\x8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u5546\u54c1',
                'verbose_name_plural': '\u8ba2\u5355\u5546\u54c1',
            },
        ),
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_sn', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\xbc\x96\xe5\x8f\xb7')),
                ('trade_no', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name=b'\xe4\xba\xa4\xe6\x98\x93\xe5\x8f\xb7')),
                ('pay_status', models.CharField(choices=[(b'TRADE_SUCCESS', b'\xe6\x88\x90\xe5\x8a\x9f'), (b'TRADE_CLOSED', b'\xe8\xb6\x85\xe6\x97\xb6\xe5\x85\xb3\xe9\x97\xad'), (b'WAIT_BUYER_PAY', b'\xe4\xba\xa4\xe6\x98\x93\xe5\x88\x9b\xe5\xbb\xba'), (b'TRADE_FINISHED', b'\xe4\xba\xa4\xe6\x98\x93\xe7\xbb\x93\xe6\x9d\x9f'), (b'PAYING', b'\xe5\xbe\x85\xe6\x94\xaf\xe4\xbb\x98')], default=b'PAYING', max_length=20, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x8a\xb6\xe6\x80\x81')),
                ('post_script', models.CharField(max_length=200, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe7\x95\x99\xe8\xa8\x80')),
                ('order_mount', models.FloatField(default=0.0, verbose_name=b'\xe8\xae\xa2\xe5\x8d\x95\xe9\x87\x91\xe9\xa2\x9d')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe6\x97\xb6\xe9\x97\xb4')),
                ('address', models.CharField(default=b'', max_length=100, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe5\x9c\xb0\xe5\x9d\x80')),
                ('signer_name', models.CharField(default=b'', max_length=20, verbose_name=b'\xe6\x94\xb6\xe8\xb4\xa7\xe4\xba\xba')),
                ('signer_mobile', models.CharField(max_length=11, verbose_name=b'\xe8\x81\x94\xe7\xb3\xbb\xe7\x94\xb5\xe8\xaf\x9d')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
            ],
            options={
                'verbose_name': '\u8ba2\u5355\u4fe1\u606f',
                'verbose_name_plural': '\u8ba2\u5355\u4fe1\u606f',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nums', models.IntegerField(default=0, verbose_name=b'\xe5\x95\x86\xe5\x93\x81\xe6\x95\xb0\xe9\x87\x8f')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name=b'\xe6\xb7\xbb\xe5\x8a\xa0\xe6\x97\xb6\xe9\x97\xb4')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name=b'\xe5\x95\x86\xe5\x93\x81')),
            ],
            options={
                'verbose_name': '\u8d2d\u7269\u8f66',
                'verbose_name_plural': '\u8d2d\u7269\u8f66',
            },
        ),
    ]
